import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import AdminClient from "@/components/AdminClient/AdminClient";
import { getCurrentUser } from "./actions/getCurrentUser";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster 
          position='top-right'
          theme="dark"
          duration={4500}
        />
        {children}
      </body>
    </html>
  );
}
